-- Sprzet budowlany
CREATE TYPE availability_status AS ENUM ('AVAILABLE', 'RENTED', 'UNAVAILABLE');
CREATE TYPE tool_category AS ENUM ('DRILL', 'CUTTER', 'SAW');

CREATE TABLE IF NOT EXISTS tool (
    tool_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_name VARCHAR(40) NOT NULL,
    tool_availability_status availability_status NOT NULL DEFAULT 'AVAILABLE',
    tool_entry_date DATE NOT NULL DEFAULT CURRENT_DATE,
    tool_description VARCHAR(100),
    tool_category tool_category NOT NULL,
    tool_price REAL NOT NULL CHECK (tool_price > 0)
);

