-- Sprzet budowlany
CREATE TYPE availability_status AS ENUM ('AVAILABLE', 'RENTED', 'UNAVAILABLE');
CREATE TYPE tool_category AS ENUM ('DRILL', 'CUTTER', 'SAW');

CREATE TABLE IF NOT EXISTS tool (
    tool_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_name VARCHAR(40) NOT NULL,
    tool_availability_status availability_status NOT NULL DEFAULT 'AVAILABLE',
    tool_entry_date DATE NOT NULL DEFAULT CURRENT_DATE,
    tool_description VARCHAR(300),
    tool_category tool_category NOT NULL,
    tool_price NUMERIC(10,2) NOT NULL CHECK (tool_price > 0)
);

-- Pracownik
CREATE TYPE employee_role AS ENUM ('REGULAR_EMPLOYEE', 'WAREHOUSE_MANAGER');

CREATE TABLE IF NOT EXISTS employee (
    employee_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name VARCHAR(25) NOT NULL,
    employee_surname VARCHAR(30) NOT NULL,
    employee_role employee_role NOT NULL,
    employee_login VARCHAR(20) NOT NULL UNIQUE,
    employee_password VARCHAR(30) NOT NULL
);

-- Klient
CREATE TABLE IF NOT EXISTS client (
    client_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name VARCHAR(25) NOT NULL,
    client_surname VARCHAR(30) NOT NULL,
    client_address VARCHAR(50) NOT NULL,
    client_mail VARCHAR(40) NOT NULL,
    client_has_duty BOOLEAN NOT NULL DEFAULT FALSE,
    client_removal_date DATE NOT NULL DEFAULT (CURRENT_DATE + INTERVAL '1 year')
);

-- Umowa
CREATE TABLE IF NOT EXISTS rental_agreement (
    agreement_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agreement_execution_date DATE NOT NULL DEFAULT CURRENT_DATE,
    agreement_estimated_termination_date DATE NOT NULL,
    agreement_actual_termination_date DATE,
    is_agreement_terminated BOOLEAN NOT NULL DEFAULT FALSE,
    client_id INT NOT NULL REFERENCES client (client_id),
    tool_id INT NOT NULL REFERENCES tool (tool_id),
    employee_id INT NOT NULL REFERENCES employee (employee_id),
    agreement_comment VARCHAR(300)
);

-- Historia sprzetu
CREATE TYPE event_category AS ENUM ('CREATION', 'UPDATE', 'DELETION');

CREATE TABLE IF NOT EXISTS tool_event (
    event_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_category event_category NOT NULL,
    event_date DATE NOT NULL DEFAULT CURRENT_DATE,
    event_comment VARCHAR(300),
    tool_id INT NOT NULL REFERENCES tool (tool_id),
    employee_id INT NOT NULL REFERENCES employee (employee_id)
);

-- Oplata
CREATE TYPE fee_category AS ENUM ('RENTAL_FEE', 'PENALTY');

CREATE TABLE IF NOT EXISTS fee (
    fee_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fee_category fee_category NOT NULL,
    agreement_id INT NOT NULL REFERENCES rental_agreement (agreement_id),
    client_id INT NOT NULL REFERENCES client (client_id),
    employee_id INT NOT NULL REFERENCES employee (employee_id),
    actual_fee NUMERIC(10,2) NOT NULL CHECK (actual_fee > 0),
    is_fee_paid BOOLEAN NOT NULL DEFAULT FALSE,
    fee_duty_date DATE NOT NULL,
    fee_finalized_date DATE
);