DROP TABLE IF EXISTS fee CASCADE;
DROP TABLE IF EXISTS tool_event CASCADE;
DROP TABLE IF EXISTS rental_agreement CASCADE;
DROP TABLE IF EXISTS client CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS tool CASCADE;

DROP TYPE IF EXISTS fee_category;
DROP TYPE IF EXISTS event_category;
DROP TYPE IF EXISTS employee_role;
DROP TYPE IF EXISTS tool_category;
DROP TYPE IF EXISTS availability_status;